## env vars
env:
  TERM: xterm-256color

## window settings
window:
  opacity: 1
  padding:
    x: 5
    y: 5


cursor:
  style: 'Block'

# def Shell
shell:
  program: /usr/bin/bash

## Font stuff
font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular

  bold:
    family: JetBrainsMono Nerd Font
    style: Bold

  italic:
    family: JetBrainsMono Nerd Font
    style: Italic

  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic

  size: 11


# General config
live_config_reload: true
draw_bold_text_with_bright_colors: true
